# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbb51e70aca6eb513f03496973ac46306bea34283c6c334dc0eeb8803f505598d420ef42902ac3dbc7e3e91c3b77eeeff70cbe60b9d9c71462715905bd517479

test:
  secret_key_base: f43a65fb41a8579407f8fc24fbafd8ef9034f713bf549f348dcb967d8fb8bef71abce088b5d3a946885c21bb54e598c3036fe3eacd773de912f4e1cb15fa81ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
